name: Push Main

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  master:
    strategy:
      matrix:
        step: ["build:release"]
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') && github.repository == 'fox-one/pando-lots'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: ${{ matrix.step }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}

      # upload to aws
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.GLOBAL_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GLOBAL_AWS_ACCESS_KEY_SECRET }}
        run: |
          cd packages/lots
          aws s3 cp --recursive dist ${{ secrets.S3_URL }} --acl public-read
          aws s3 cp dist/index.html ${{ secrets.S3_URL }} --cache-control "no-cache" --acl public-read

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
